name: assignment-test

on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'

jobs:
    full-test:
        runs-on: self-hosted

        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'

          - uses: webfactory/ssh-agent@v0.5.4
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Run full test
            timeout-minutes: 15
            run: |
              docker run --rm \
                -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                -v /home/jayanth/CUB_EmbedLinux/Course2/aeld-assignment-6/poky:/persistent-poky \
                -v /home/jayanth/CUB_EmbedLinux/Course2/aeld-assignment-6/build:/home/jayanth/CUB_EmbedLinux/Course2/aeld-assignment-6/build \
                -e SKIP_BUILD=1 \
                -e DO_VALIDATE=1 \
                -e POKY_DIR=/persistent-poky \
                -e BUILD_DIR=/persistent-build \
                cuaesd/aesd-autotest:assignment6-yocto \
                --workdir=${GITHUB_WORKSPACE} \
                ./full-test.sh

          - name: Cleanup
            if: always()
            run: |
              ssh-add -D